services:
  app:
    image: ${APP_IMAGE:-ghcr.io/yorch/bilinear:main}
    pull_policy: always
    restart: unless-stopped
    init: true
    ports:
      - ${APP_PORT:-3000}:3000
    env_file:
      - .env
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      DATABASE_URL: ${DATABASE_URL_OVERRIDE:-postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-issue_tracker}}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
